spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yolofarm_db
    username: postgres
    password: 23012005
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
