@startuml
package "Observer Pattern (Nhận Dữ liệu Cảm biến)" {
    interface Subject {
        + attach(obs: Observer)
        + detach(obs: Observer)
        + notifyObservers(deviceId: UUID, metricType: String, value: Float)
    }

    class MqttReceiverService {
        - observers: List<Observer>
        + onMessageReceived(topic: String, payload: String)
        + notifyObservers(deviceId: UUID, metricType: String, value: Float)
    }
    Subject <|.. MqttReceiverService

    interface Observer {
        + update(deviceId: UUID, metricType: String, value: Float)
    }
    MqttReceiverService o--> "*" Observer : Manages

    class DatabaseLoggerObserver {
        + update(deviceId: UUID, metricType: String, value: Float)
        - saveToTimeSeriesDB()
    }
    class WebSocketNotifierObserver {
        + update(deviceId: UUID, metricType: String, value: Float)
        - pushToReactFrontend()
    }
    class RuleEngineObserver {
        + update(deviceId: UUID, metricType: String, value: Float)
        - checkSensorConditions()
    }
    
    Observer <|.. DatabaseLoggerObserver
    Observer <|.. WebSocketNotifierObserver
    Observer <|.. RuleEngineObserver
}
@enduml